# DATA TYPES IN NUMPY


In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
arr


array([1, 2, 3, 4, 5])

In [6]:
arr.dtype

dtype('int64')

In [7]:
arr.astype("float32")

array([1., 2., 3., 4., 5.], dtype=float32)

In [10]:
arr.nbytes

40

In [11]:
arr.astype("int32")

array([1, 2, 3, 4, 5], dtype=int32)

In [12]:
arr.nbytes

40

In [13]:
arr2 = np.array(arr,dtype="int32")

In [14]:
arr2

array([1, 2, 3, 4, 5], dtype=int32)