# 2D array

In [1]:
import numpy as np


In [2]:
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
arr2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr2D[0]

array([1, 2, 3])

In [5]:
arr2D[1,2]

np.int64(6)

In [6]:
arr2D[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [7]:
arr2D.sum(axis=1)

array([ 6, 15, 24])

In [8]:
arr2D.sum(axis=0)

array([12, 15, 18])

# 3D array

In [9]:
arr3D = np.array([
    [
        [1,2,3,4],
        [5,6,7,8]
    ],
    [
        [1,2,3,4],
        [5,6,7,8]
    ]
])

In [10]:
arr3D


array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [12]:
arr3D.shape


(2, 2, 4)

In [14]:
arr3D[:,0,:]

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])