In [2]:
import numpy as np

In [8]:
arr = np.random.randint(1,51,size=(3,3))

In [9]:
arr

array([[24, 18, 37],
       [44, 13, 26],
       [11, 40, 41]], dtype=int32)

In [11]:
arr.shape

(3, 3)

In [12]:
myarr = np.random.rand(3,3)

In [15]:
print(myarr)
myarr.dtype


[[0.75383146 0.46333055 0.07871416]
 [0.56876419 0.73312431 0.58636499]
 [0.13397185 0.67767006 0.88770089]]


dtype('float64')

In [21]:
print(myarr.astype(int))
myarr.dtype

[[0 0 0]
 [0 0 0]
 [0 0 0]]


dtype('float64')

In [23]:
arr1 = np.array([1,2,3,4,5,6])

In [26]:
arr1[arr1 % 2 == 0]

array([2, 4, 6])

In [27]:
arr3 = np.random.randint(1,10,size=(9))

In [ ]:
arr3
